version: "3.8"

services:
  web:
    image: ghcr.io/entu/www:latest

    # Published in ingress mode
    ports:
      - target: 8080
        published: ${PORT:-8080}
        mode: ingress
        protocol: tcp

    # Attach to both your overlay network and ingress
    networks:
      - vpc-overlay
      - ingress

    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    security_opt:
      - no-new-privileges:true

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      interval: 10s
      timeout: 2s
      retries: 3

# Networks
networks:
  vpc-overlay:
    external: true
  ingress:
    external: true
